server:
  port: 8085

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_rainng_course?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: EternityTQ@123
  jackson:
    time-zone: Asia/Shanghai

mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.rainng.coursesystem.model
